version: '3.8'

services:
  server:
    build: ./server
    container_name: basic_backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_HOST: database-1.coxwukq4kdkr.us-east-1.rds.amazonaws.com
      DB_NAME: postgres
      DB_PASSWORD: "kau_(shik)*1"
      DB_PORT: 5432
      DB_SSL: "true"

  client:
    build: ./client
    container_name: basic_frontend
    ports:
      - "80:80"
    depends_on:
      - server
