version: '3.8'

services:
  server:
    build: ./server
    container_name: basic_backend
    ports:
      - "3000:3000"
    env_file:
      - .env

  client:
    build: ./client
    container_name: basic_frontend
    ports:
      - "80:80"
    depends_on:
      - server
