version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: basic_postgres
    environment:
      POSTGRES_USER: database-1.coxwukq4kdkr.us-east-1.rds.amazonaws.com
      POSTGRES_PASSWORD: kau_(shik)*1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: basic_backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - db

  client:
    build: ./client
    container_name: basic_frontend
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  pgdata:
